### ISSUE TITLE
Linking Python to Fortran

### ISSUE THREAD

**Issue by dnathanbradley** [csdms/help-desk#7]
Is there the capability in BMI in PyMT to link Python and Fortran code? I've heard that it can be done, but I haven't found any documentation about it. 

Specifically, I have an existing Fortran 90 code that defines a bunch of different sediment transport capacity functions. I'd like to be able to call these functions using Python to compute sediment transport from hydraulic model results that are stored in ArcMap shapefiles. I have spent several days trying to use numpy.f2py, with no success.

**Comment by mdpiper** [comment]
@dnathanbradley  Here's an overview of the technique we used at CSDMS to access Fortran code in Python.

1. Write, in Fortran, an interoperability layer. Each function that you want to expose in Python is wrapped with a function that uses only C types from the Fortran 2003 `iso_c_binding` module. These wrapper functions can be compiled into a C library and called from C.
1. Write Cython code that calls the wrapper functions in the interoperability layer.
1. Set up a Python package for your Cython code. Cython will compile and link your wrapper code. Your wrapped functions can then be called in Python and there's no trace of the fact that you're really calling Fortran under the hood.

This process isn't easy, but it is doable. I'll point to some sample code that shows how BMI is wrapped using this technique.

**Comment by mdpiper** [comment]
Here's an example of taking a function from Fortran -> interoperable Fortran -> Cython -> Python. It's BMI, so there's extra stuff, but I think it shows the gist of the technique.

Start at the *heat_grid_shape* function on line 311 of [bmi_heat.f90](https://github.com/csdms/bmi-example-fortran/blob/master/bmi_heat/bmi_heat.f90). This function takes a grid index as input, and passes out, as a parameter, a 1D array `[nrows, ncols, ...]` describing a model grid. The function return is just 0 or 1. This is all plain Fortran.

Next, look at the *bmi_get_grid_shape* function on line 322 of [bmi_interoperability.f90](https://github.com/mdpiper/pymt_heatf/blob/master/pymt_heatf/lib/bmi_interoperability.f90). This function uses only C types imported from the `iso_c_binding` module. It can be compiled into a C library. This function is just a wrapper; all it does is call the *heat_grid_shape* function described above.

Because *bmi_get_grid_shape* can be compiled to C, we can write a function prototype for it, as shown in line 36 of [bmi_interoperability.h](https://github.com/mdpiper/pymt_heatf/blob/master/pymt_heatf/lib/bmi_interoperability.h).

This function prototype is used to define a Cython function, *get_grid_shape*, as shown on line 273 of [heatf.pyx](https://github.com/mdpiper/pymt_heatf/blob/master/pymt_heatf/lib/heatf.pyx). The Cython code uses C language features.

Finally, the *get_grid_shape* function can be called in Python. See, e.g., line 53 of [heatf_ex.py](https://github.com/mdpiper/pymt_heatf/blob/master/examples/heatf_ex.py).

I've passed over important details, like how to set up and use Cython, but I think these examples outline our technique.

**Comment by mdpiper** [comment]
@dnathanbradley I now have a process set up where I can wrap a Fortran model with a BMI in Python and run it in [pymt](https://github.com/csdms/pymt). All I need is a Fortran model with the latest [BMI](https://github.com/csdms/bmi-fortran). Let me know if this would be helpful.

**Comment by mdpiper** [comment]
Closing this issue. We have a good path from Fortran to Python through *pymt*. All that's required of a user is a [Fortran BMI](https://github.com/csdms/bmi-fortran) on their code, and we provide an [example](https://github.com/csdms/bmi-example-fortran) to guide them.
